// Copyright (c) 2023-2026 ktsu-dev contributors

namespace ktsu.Semantics.Test.Quantities;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.VisualStudio.TestTools.UnitTesting;
// Fully qualified: inside namespace ktsu.Semantics.Test, a bare "Semantics.SourceGenerators"
// would bind to ktsu.Semantics.SourceGenerators, which does not exist.
using global::Semantics.SourceGenerators;

/// <summary>
/// Drives the incremental source generators directly through <see cref="CSharpGeneratorDriver"/>.
/// </summary>
/// <remarks>
/// The committed output under <c>Semantics.Quantities/Generated/</c> is already covered indirectly by
/// <c>GeneratorOutputInvariantTests</c>, which reflects over the compiled types. These tests
/// instead exercise the generators themselves, so that the emitted file header and the
/// metadata-to-source pipeline are guarded rather than only their end product. Without them a change
/// to <c>GeneratorBase.WriteHeaderTo</c> is invisible until the committed sources drift out of sync
/// with what the generator produces, which fails the verify-generated workflow rather than a test.
/// </remarks>
[TestClass]
public class SourceGeneratorTests
{
	/// <summary>The header every generated file is expected to begin with.</summary>
	private const string ExpectedHeader = "// Copyright (c) 2023-2026 ktsu-dev contributors\n// <auto-generated />";

	private static string MetadataDirectory => Path.Combine(AppContext.BaseDirectory, "GeneratorMetadata");

	private static GeneratorHarness Harness => new(MetadataDirectory);

	/// <summary>
	/// Every generator paired with the metadata file it consumes.
	/// </summary>
	private static IEnumerable<(IIncrementalGenerator Generator, string MetadataFileName)> Generators =>
	[
		(new ConversionsGenerator(), "conversions.json"),
		(new DimensionsGenerator(), "dimensions.json"),
		(new LogarithmicScalesGenerator(), "logarithmic.json"),
		(new MagnitudesGenerator(), "magnitudes.json"),
		(new PhysicalConstantsGenerator(), "domains.json"),
		(new PrecisionGenerator(), "precision.json"),
		(new QuantitiesGenerator(), "dimensions.json"),
		(new UnitsGenerator(), "units.json"),
	];

	// Iterates inside the test rather than using [DynamicData] with an IIncrementalGenerator
	// parameter: a public test method taking a reference type trips CA1062, and neither escape is
	// available here - CA1510 rejects an explicit ArgumentNullException throw, CA1062 does not
	// recognise ArgumentNullException.ThrowIfNull, and Polyfill's Ensure cannot be referenced
	// because its shim types collide with the ones the generator assembly embeds publicly.
	// Assertion messages name the generator, so a failure is still unambiguous.
	[TestMethod]
	public void EveryGenerator_EmitsSourcesWithTheCanonicalHeader()
	{
		foreach ((IIncrementalGenerator generator, string metadataFileName) in Generators)
		{
			string generatorName = generator.GetType().Name;
			GeneratorRunResult result = Harness.Run(generator);

			Assert.IsEmpty(
				result.Diagnostics,
				$"{generatorName} reported diagnostics: {string.Join("; ", result.Diagnostics.Select(d => d.GetMessage()))}");

			Assert.IsGreaterThan(
				0,
				result.GeneratedSources.Length,
				$"{generatorName} produced no sources from {metadataFileName}.");

			foreach (GeneratedSourceResult source in result.GeneratedSources)
			{
				// Normalise newlines so the assertion does not depend on the host platform.
				string text = source.SourceText.ToString().Replace("\r\n", "\n", StringComparison.Ordinal);

				Assert.StartsWith(
					ExpectedHeader,
					text,
					$"{generatorName} emitted {source.HintName} without the expected file header. " +
					$"GeneratorBase.WriteHeaderTo must stay in step with file_header_template in .editorconfig, " +
					$"otherwise every generated file fails IDE0073.");
			}
		}
	}

	[TestMethod]
	public void QuantitiesGenerator_EmitsTheExpectedBreadthOfTypes()
	{
		GeneratorRunResult result = Harness.Run(new QuantitiesGenerator());

		// Sanity bound: the dimensions metadata drives a large catalogue, so a collapse to a handful
		// of sources means the metadata or the filter regressed rather than that the shape changed.
		Assert.IsGreaterThan(50, result.GeneratedSources.Length);
	}

	[TestMethod]
	public void Generator_WithMalformedMetadata_ReportsDiagnosticInsteadOfThrowing()
	{
		GeneratorRunResult result = Harness.Run(
			new PrecisionGenerator(),
			new Dictionary<string, string> { ["precision.json"] = "{ not valid json" });

		Assert.IsEmpty(result.GeneratedSources);
		Assert.IsNotEmpty(result.Diagnostics, "Malformed metadata should surface as a diagnostic.");
		Assert.AreEqual("SEM007", result.Diagnostics[0].Id);
	}

	[TestMethod]
	public void EveryGenerator_ReusesItsOutputWhenTheMetadataHasNotChanged()
	{
		// These are IIncrementalGenerators, and nothing checked that they behave like one: a
		// generator that recomputes everything on every keystroke still passes every output
		// assertion, it just makes the IDE slow.
		foreach ((IIncrementalGenerator generator, string _) in Generators)
		{
			Assert.IsTrue(
				Harness.ReusesCachedOutputOnRerun(generator),
				$"{generator.GetType().Name} recomputed its output for unchanged metadata.");
		}
	}
}
