// Copyright (c) 2023-2026 ktsu-dev contributors

namespace ktsu.Semantics.Test.Quantities;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.VisualStudio.TestTools.UnitTesting;
// Fully qualified: inside namespace ktsu.Semantics.Test, a bare "Semantics.SourceGenerators"
// would bind to ktsu.Semantics.SourceGenerators, which does not exist.
using global::Semantics.SourceGenerators;
using global::ktsu.SourceGeneratorToolkit.Testing;

/// <summary>
/// Drives the incremental source generators directly through <see cref="CSharpGeneratorDriver"/>.
/// </summary>
/// <remarks>
/// The committed output under <c>Semantics.Quantities/Generated/</c> is already covered indirectly by
/// <c>GeneratorOutputInvariantTests</c>, which reflects over the compiled types. These tests
/// instead exercise the generators themselves, so that the emitted file header and the
/// metadata-to-source pipeline are guarded rather than only their end product. Without them a change
/// to <c>GeneratorBase.WriteHeaderTo</c> is invisible until the committed sources drift out of sync
/// with what the generator produces, which fails the verify-generated workflow rather than a test.
/// </remarks>
[TestClass]
public class SourceGeneratorTests
{
	/// <summary>The header every generated file is expected to begin with.</summary>
	private const string ExpectedHeader = "// Copyright (c) 2023-2026 ktsu-dev contributors\n// <auto-generated />";

	/// <summary>The sentence every logarithmic conversion computing in double is expected to carry.</summary>
	private const string DoublePrecisionRemark =
		"Computes in <see langword=\"double\"/> whatever <typeparamref name=\"T\"/> is";

	/// <summary>The line that marks a conversion body actually dropping to double.</summary>
	private const string DoubleConversionMarker = "= double.CreateChecked(";

	private static string MetadataDirectory => Path.Combine(AppContext.BaseDirectory, "GeneratorMetadata");

	private static GeneratorHarness Harness => new(MetadataDirectory);

	/// <summary>
	/// Every generator paired with the metadata file it consumes.
	/// </summary>
	private static IEnumerable<(IIncrementalGenerator Generator, string MetadataFileName)> Generators =>
	[
		(new ConversionsGenerator(), "conversions.json"),
		(new DimensionsGenerator(), "dimensions.json"),
		(new LogarithmicScalesGenerator(), "logarithmic.json"),
		(new MagnitudesGenerator(), "magnitudes.json"),
		(new PhysicalConstantsGenerator(), "domains.json"),
		(new PrecisionGenerator(), "precision.json"),
		(new QuantitiesGenerator(), "dimensions.json"),
		(new UnitsGenerator(), "units.json"),
	];

	// Iterates inside the test rather than using [DynamicData] with an IIncrementalGenerator
	// parameter: a public test method taking a reference type trips CA1062, and neither escape is
	// available here - CA1510 rejects an explicit ArgumentNullException throw, CA1062 does not
	// recognise ArgumentNullException.ThrowIfNull, and Polyfill's Ensure cannot be referenced
	// because its shim types collide with the ones the generator assembly embeds publicly.
	// Assertion messages name the generator, so a failure is still unambiguous.
	[TestMethod]
	public void EveryGenerator_EmitsSourcesWithTheCanonicalHeader()
	{
		foreach ((IIncrementalGenerator generator, string metadataFileName) in Generators)
		{
			string generatorName = generator.GetType().Name;
			GeneratorRunResult result = Harness.Run(generator);

			// SEM008 is excluded because the real metadata declares five relationships that are not
			// dimensionally true, all documented in CLAUDE.md and none of them a spelling mistake.
			// UnkeepableRelationshipTests pins that set to exactly those five, so excluding the
			// identifier here does not let a sixth through.
			IEnumerable<Diagnostic> unexpected =
				result.Diagnostics.Where(diagnostic => diagnostic.Id != "SEM008");

			Assert.IsEmpty(
				unexpected,
				$"{generatorName} reported diagnostics: {string.Join("; ", unexpected.Select(d => d.GetMessage()))}");

			Assert.IsGreaterThan(
				0,
				result.GeneratedSources.Length,
				$"{generatorName} produced no sources from {metadataFileName}.");

			foreach (GeneratedSourceResult source in result.GeneratedSources)
			{
				// Normalise newlines so the assertion does not depend on the host platform.
				string text = source.SourceText.ToString().Replace("\r\n", "\n", StringComparison.Ordinal);

				Assert.StartsWith(
					ExpectedHeader,
					text,
					$"{generatorName} emitted {source.HintName} without the expected file header. " +
					$"GeneratorBase.WriteHeaderTo must stay in step with file_header_template in .editorconfig, " +
					$"otherwise every generated file fails IDE0073.");
			}
		}
	}

	[TestMethod]
	public void QuantitiesGenerator_EmitsTheExpectedBreadthOfTypes()
	{
		GeneratorRunResult result = Harness.Run(new QuantitiesGenerator());

		// Sanity bound: the dimensions metadata drives a large catalogue, so a collapse to a handful
		// of sources means the metadata or the filter regressed rather than that the shape changed.
		Assert.IsGreaterThan(50, result.GeneratedSources.Length);
	}

	/// <summary>
	/// Every logarithmic-scale conversion that computes in <see langword="double"/> carries XML
	/// remarks saying so.
	/// </summary>
	/// <remarks>
	/// The conversions convert to <see langword="double"/>, take the logarithm or power there, and
	/// convert back, so a <see langword="decimal"/> or <c>PreciseNumber</c> scale keeps about fifteen
	/// significant digits across one. Everything else about these types is exact in the storage type,
	/// which is what makes the drop worth stating at the call site rather than leaving to be found in
	/// a result. Counted rather than spot-checked, so a conversion added later cannot ship
	/// undocumented.
	/// </remarks>
	[TestMethod]
	public void LogarithmicScalesGenerator_DocumentsEveryConversionThatComputesInDouble()
	{
		GeneratorRunResult result = Harness.Run(new LogarithmicScalesGenerator());

		Assert.IsGreaterThan(0, result.GeneratedSources.Length, "LogarithmicScalesGenerator produced no sources.");

		int documented = 0;
		foreach (GeneratedSourceResult source in result.GeneratedSources)
		{
			string text = source.SourceText.ToString();
			int conversions = Occurrences(text, DoubleConversionMarker);
			int remarks = Occurrences(text, DoublePrecisionRemark);

			Assert.AreEqual(
				conversions,
				remarks,
				$"{source.HintName} has {conversions} conversion(s) computing in double but {remarks} " +
				$"carrying the precision remarks. A conversion that drops to double has to say so in " +
				$"its own XML docs, because the method's tooltip is where a caller spending that " +
				$"precision would see it.");

			documented += remarks;
		}

		// Reaching zero would mean the double path is gone — issue #235's option 3 landed, and the
		// conversions compute in T's own arithmetic. The remarks would then be false and should be
		// removed along with this test, rather than this assertion being relaxed.
		Assert.IsGreaterThan(0, documented, "No logarithmic-scale conversion carries the precision remarks.");
	}

	/// <summary>
	/// Counts non-overlapping occurrences of a substring.
	/// </summary>
	/// <param name="text">The text to search.</param>
	/// <param name="value">The substring to count.</param>
	/// <returns>The number of occurrences.</returns>
	private static int Occurrences(string text, string value)
	{
		int count = 0;
		for (int index = text.IndexOf(value, StringComparison.Ordinal);
			index >= 0;
			index = text.IndexOf(value, index + value.Length, StringComparison.Ordinal))
		{
			count++;
		}

		return count;
	}

	[TestMethod]
	public void Generator_WithMalformedMetadata_ReportsDiagnosticInsteadOfThrowing()
	{
		GeneratorRunResult result = Harness.Run(
			new PrecisionGenerator(),
			new Dictionary<string, string> { ["precision.json"] = "{ not valid json" });

		Assert.IsEmpty(result.GeneratedSources);
		Assert.IsNotEmpty(result.Diagnostics, "Malformed metadata should surface as a diagnostic.");
		Assert.AreEqual("SEM007", result.Diagnostics[0].Id);
	}

	[TestMethod]
	public void EveryGenerator_ReusesItsOutputWhenTheMetadataHasNotChanged()
	{
		// These are IIncrementalGenerators, and nothing checked that they behave like one: a
		// generator that recomputes everything on every keystroke still passes every output
		// assertion, it just makes the IDE slow.
		foreach ((IIncrementalGenerator generator, string _) in Generators)
		{
			Assert.IsTrue(
				Harness.ReusesCachedOutputOnRerun(generator),
				$"{generator.GetType().Name} recomputed its output for unchanged metadata.");
		}
	}
}
