<#
.SYNOPSIS
	Generates the per-storage-type alias .props files for the
	ktsu.Semantics.Quantities.<StorageType> satellite packages.

.DESCRIPTION
	Each satellite package ships a buildTransitive/<PackageId>.props that NuGet
	auto-imports into consumers. The props inject MSBuild <Using> items, which the
	SDK turns into `global using Mass = ktsu.Semantics.Quantities.Mass<double>;`
	(and so on for every quantity type), so a project that references the package
	can write `Mass` instead of `Mass<double>`.

	The catalog of quantity types is the set of committed source-generator outputs
	(every quantity is emitted as a `<Type>.g.cs`), so this script stays in sync
	with the generator automatically. It writes nothing but the .props files and is
	verified in CI (see .github/workflows/verify-generated.yml).
#>
[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
$generatedRoot = Join-Path $repoRoot 'Semantics.Quantities/Generated/Semantics.SourceGenerators'

# Every generic quantity type is emitted by one of these generators as <Type>.g.cs.
$catalogDirs = @(
	'Semantics.SourceGenerators.QuantitiesGenerator',
	'Semantics.SourceGenerators.LogarithmicScalesGenerator'
)

$typeNames = foreach ($dir in $catalogDirs) {
	$path = Join-Path $generatedRoot $dir
	if (Test-Path $path) {
		Get-ChildItem -Path $path -Filter '*.g.cs' -File |
			ForEach-Object { $_.Name -replace '\.g\.cs$', '' }
	}
}

$typeNames = $typeNames | Sort-Object -Unique -Culture ([System.Globalization.CultureInfo]::InvariantCulture)

if ($typeNames.Count -eq 0) {
	throw "No quantity types found under $generatedRoot. Build Semantics.Quantities first so the generated files exist."
}

# PascalCase project/package suffix => C# storage keyword.
$storageTypes = [ordered]@{
	'Double'  = 'double'
	'Float'   = 'float'
	'Decimal' = 'decimal'
}

foreach ($entry in $storageTypes.GetEnumerator()) {
	$suffix = $entry.Key
	$keyword = $entry.Value
	$packageId = "ktsu.Semantics.Quantities.$suffix"
	$projectDir = Join-Path $repoRoot "Semantics.Quantities.$suffix"
	$buildTransitive = Join-Path $projectDir 'buildTransitive'
	New-Item -ItemType Directory -Path $buildTransitive -Force | Out-Null

	$sb = [System.Text.StringBuilder]::new()
	[void]$sb.AppendLine('<Project>')
	[void]$sb.AppendLine("`t<!-- Auto-generated by scripts/Generate-AliasProps.ps1. Do not edit by hand. -->")
	[void]$sb.AppendLine("`t<!-- Aliases every ktsu.Semantics.Quantities type to <$keyword> so consumers omit the generic argument. -->")
	[void]$sb.AppendLine("`t<ItemGroup>")
	foreach ($name in $typeNames) {
		[void]$sb.AppendLine("`t`t<Using Include=`"ktsu.Semantics.Quantities.$name&lt;$keyword&gt;`" Alias=`"$name`" />")
	}
	[void]$sb.AppendLine("`t</ItemGroup>")
	[void]$sb.AppendLine('</Project>')

	$propsPath = Join-Path $buildTransitive "$packageId.props"
	# CRLF to match the repo's line-ending convention.
	$content = ($sb.ToString() -replace "`r?`n", "`r`n")
	[System.IO.File]::WriteAllText($propsPath, $content, [System.Text.UTF8Encoding]::new($false))
	Write-Host "Wrote $propsPath ($($typeNames.Count) aliases)"
}
