<#
.SYNOPSIS
	Generates the per-storage-type alias .props files for the
	ktsu.Semantics.Quantities.<StorageType> satellite packages.

.DESCRIPTION
	Each satellite package ships a build/<PackageId>.props that NuGet auto-imports
	into the project that references the package. The props inject MSBuild <Using>
	items, which the SDK turns into
	`global using Mass = ktsu.Semantics.Quantities.Mass<double>;` (and so on for
	every quantity type), so a project that references the package can write `Mass`
	instead of `Mass<double>`.

	build/ rather than buildTransitive/ on purpose. The alias names are project-wide
	global usings keyed on the bare type name, so two storage types reaching one
	project define every alias twice and the compile fails with one CS1537 per
	quantity. buildTransitive/ flows the binding to every project downstream of the
	referencing one, so a project that references no alias package at all - and
	therefore cannot satisfy the "one alias package per project" rule - would collect
	two. build/ binds exactly where the reference is, which is what the rule says.

	The catalog of quantity types is the set of committed source-generator outputs
	(every quantity is emitted as a `<Type>.g.cs`), so this script stays in sync
	with the generator automatically. It writes nothing but the .props files and is
	verified in CI (see .github/workflows/verify-generated.yml).
#>
[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
$generatedRoot = Join-Path $repoRoot 'Semantics.Quantities/Generated/Semantics.SourceGenerators'

# Every generic quantity type is emitted by one of these generators as <Type>.g.cs.
$catalogDirs = @(
	'Semantics.SourceGenerators.QuantitiesGenerator',
	'Semantics.SourceGenerators.LogarithmicScalesGenerator'
)

$typeNames = foreach ($dir in $catalogDirs) {
	$path = Join-Path $generatedRoot $dir
	if (Test-Path $path) {
		Get-ChildItem -Path $path -Filter '*.g.cs' -File |
			ForEach-Object { $_.Name -replace '\.g\.cs$', '' }
	}
}

$typeNames = $typeNames | Sort-Object -Unique -Culture ([System.Globalization.CultureInfo]::InvariantCulture)

if ($typeNames.Count -eq 0) {
	throw "No quantity types found under $generatedRoot. Build Semantics.Quantities first so the generated files exist."
}

# PascalCase project/package suffix => the storage type as it is written in the alias.
# A keyword for the built-in types; a fully qualified name for one that comes from a package,
# since the alias is expanded in projects that have no using directives of ours.
$storageTypes = [ordered]@{
	'Double'  = 'double'
	'Float'   = 'float'
	'Decimal' = 'decimal'
	'Precise' = 'ktsu.PreciseNumber.PreciseNumber'
}

foreach ($entry in $storageTypes.GetEnumerator()) {
	$suffix = $entry.Key
	$keyword = $entry.Value
	$packageId = "ktsu.Semantics.Quantities.$suffix"
	$projectDir = Join-Path $repoRoot "Semantics.Quantities.$suffix"
	$buildFolder = Join-Path $projectDir 'build'
	New-Item -ItemType Directory -Path $buildFolder -Force | Out-Null

	$sb = [System.Text.StringBuilder]::new()
	[void]$sb.AppendLine('<Project>')
	[void]$sb.AppendLine("`t<!-- Auto-generated by scripts/Generate-AliasProps.ps1. Do not edit by hand. -->")
	[void]$sb.AppendLine("`t<!-- Aliases every ktsu.Semantics.Quantities type to <$keyword> so consumers omit the generic argument. -->")
	[void]$sb.AppendLine("`t<ItemGroup>")
	foreach ($name in $typeNames) {
		[void]$sb.AppendLine("`t`t<Using Include=`"ktsu.Semantics.Quantities.$name&lt;$keyword&gt;`" Alias=`"$name`" />")
	}
	[void]$sb.AppendLine("`t</ItemGroup>")
	[void]$sb.AppendLine('</Project>')

	$propsPath = Join-Path $buildFolder "$packageId.props"
	# CRLF to match the repo's line-ending convention.
	$content = ($sb.ToString() -replace "`r?`n", "`r`n")
	[System.IO.File]::WriteAllText($propsPath, $content, [System.Text.UTF8Encoding]::new($false))
	Write-Host "Wrote $propsPath ($($typeNames.Count) aliases)"
}
